// src/Elsa.Dashboard.Vue/src/components/ExpenseList.vue
<template>
    <v-card v-if="expenses.length > 0">
      <v-list>
        <ExpenseItem
          v-for="expense in expenses"
          :key="expense.id"
          :expense="expense"
        />
      </v-list>
    </v-card>
  
    <v-alert v-else type="info" text>
      No expenses found.
    </v-alert>
  </template>
  
  <script lang="ts">
  import { defineComponent } from 'vue';
  import ExpenseItem from './ExpenseItem.vue';
  import { Expense } from '@/interfaces/Expense';
  
  export default defineComponent({
    name: 'ExpenseList',
    components: {
      ExpenseItem,
    },
    props: {
      expenses: {
        type: Array as () => Expense[],
        required: true,
      },
    },
  });
  </script>

// src/Elsa.DashboardReact/src/components/ExpenseList.tsx
import React from 'react';
import { Expense } from '../interfaces/Expense';
import ExpenseItem from './ExpenseItem';
import { List, Typography, Paper } from '@mui/material';

interface ExpenseListProps {
  expenses: Expense[];
}

const ExpenseList: React.FC<ExpenseListProps> = ({ expenses }) => {
  if (expenses.length === 0) {
    return (
      <Typography variant="h6" align="center">
        No expenses found.
      </Typography>
    );
  }

  return (
    <Paper style={{ padding: '16px' }}>
      <List>
        {expenses.map((expense) => (
          <ExpenseItem key={expense.id} expense={expense} />
        ))}
      </List>
    </Paper>
  );
};

export default ExpenseList;
