// src/Elsa.Dashboard.Vue/src/components/FilterOptions.vue
<template>
    <v-card>
      <v-card-title>Filter Expenses</v-card-title>
  
      <v-row>
        <!-- Category Filter -->
        <v-col cols="12" md="4">
          <v-select
            v-model="filters.category"
            :items="categories"
            label="Category"
          />
        </v-col>
  
        <!-- Start Date Filter -->
        <v-col cols="12" md="4">
          <v-text-field
            v-model="filters.startDate"
            label="Start Date"
            type="date"
            :value="formattedStartDate"
            @change="handleStartDateChange"
          />
        </v-col>
  
        <!-- End Date Filter -->
        <v-col cols="12" md="4">
          <v-text-field
            v-model="filters.endDate"
            label="End Date"
            type="date"
            :value="formattedEndDate"
            @change="handleEndDateChange"
          />
        </v-col>
      </v-row>
    </v-card>
  </template>
  
  <script lang="ts">
  import { defineComponent, ref, computed } from 'vue';
  
  export default defineComponent({
    name: 'FilterOptions',
    props: {
      filters: {
        type: Object as () => {
          category: string;
          startDate: Date | null;
          endDate: Date | null;
        },
        required: true,
      },
      onUpdateFilters: {
        type: Function,
        required: true,
      },
    },
    setup(props) {
      const categories = ref(['', 'Food', 'Travel', 'Entertainment', 'Utilities']);
  
      const handleStartDateChange = (e: Event) => {
        const target = e.target as HTMLInputElement;
        const startDate = target.value ? new Date(target.value) : null;
        props.onUpdateFilters({ ...props.filters, startDate });
      };
  
      const handleEndDateChange = (e: Event) => {
        const target = e.target as HTMLInputElement;
        const endDate = target.value ? new Date(target.value) : null;
        props.onUpdateFilters({ ...props.filters, endDate });
      };
  
      const formattedStartDate = computed(() =>
        props.filters.startDate ? props.filters.startDate.toISOString().split('T')[0] : ''
      );
      const formattedEndDate = computed(() =>
        props.filters.endDate ? props.filters.endDate.toISOString().split('T')[0] : ''
      );
  
      return {
        categories,
        handleStartDateChange,
        handleEndDateChange,
        formattedStartDate,
        formattedEndDate,
      };
    },
  });
  </script>

// src/Elsa.DashboardReact/src/components/FilterOptions.tsx
import React from 'react';
import {
  TextField,
  MenuItem,
  Paper,
  Typography,
  Box,
} from '@mui/material';

interface FilterOptionsProps {
  filters: {
    category: string;
    startDate: Date | null;
    endDate: Date | null;
  };
  onUpdateFilters: (filters: {
    category: string;
    startDate: Date | null;
    endDate: Date | null;
  }) => void;
}

const FilterOptions: React.FC<FilterOptionsProps> = ({
  filters,
  onUpdateFilters,
}) => {
  const handleCategoryChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onUpdateFilters({ ...filters, category: e.target.value });
  };

  const handleStartDateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onUpdateFilters({
      ...filters,
      startDate: e.target.value ? new Date(e.target.value) : null,
    });
  };

  const handleEndDateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onUpdateFilters({
      ...filters,
      endDate: e.target.value ? new Date(e.target.value) : null,
    });
  };

  return (
    <Paper style={{ padding: '16px', marginBottom: '16px' }}>
      <Typography variant="h6" gutterBottom>
        Filter Expenses
      </Typography>
      <Box
        component="div"
        sx={{
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' },
          gap: 2,
        }}
      >
        {/* Category Filter */}
        <TextField
          label="Category"
          select
          fullWidth
          value={filters.category}
          onChange={handleCategoryChange}
        >
          <MenuItem value="">All</MenuItem>
          <MenuItem value="Food">Food</MenuItem>
          <MenuItem value="Travel">Travel</MenuItem>
          <MenuItem value="Entertainment">Entertainment</MenuItem>
          <MenuItem value="Utilities">Utilities</MenuItem>
        </TextField>

        {/* Start Date Filter */}
        <TextField
          label="Start Date"
          type="date"
          fullWidth
          value={
            filters.startDate
              ? filters.startDate.toISOString().split('T')[0]
              : ''
          }
          onChange={handleStartDateChange}
          InputLabelProps={{
            shrink: true,
          }}
        />

        {/* End Date Filter */}
        <TextField
          label="End Date"
          type="date"
          fullWidth
          value={
            filters.endDate
              ? filters.endDate.toISOString().split('T')[0]
              : ''
          }
          onChange={handleEndDateChange}
          InputLabelProps={{
            shrink: true,
          }}
        />
      </Box>
    </Paper>
  );
};

export default FilterOptions;
