// src/Elsa.DashboardReact/src/components/TotalExpenditure.tsx
import React from 'react';
import { Expense } from '../interfaces/Expense';
import { Typography, Paper } from '@mui/material';

interface TotalExpenditureProps {
  expenses: Expense[];
}

const TotalExpenditure: React.FC<TotalExpenditureProps> = ({ expenses }) => {
  const total = expenses.reduce((sum, expense) => sum + expense.amount, 0);

  return (
    <Paper style={{ padding: '16px', marginBottom: '16px' }}>
      <Typography variant="h5" align="center">
        Total Expenditure: £{total.toFixed(2)}
      </Typography>
    </Paper>
  );
};

export default TotalExpenditure;

// src/Elsa.Dashboard.Vue/src/components/TotalExpenditure.vue
<template>
    <v-card>
      <v-card-title>Total Expenditure: £{{ total }}</v-card-title>
    </v-card>
  </template>
  
  <script lang="ts">
  import { defineComponent, computed } from 'vue';
  import { Expense } from '@/interfaces/Expense';
  
  export default defineComponent({
    name: 'TotalExpenditure',
    props: {
      expenses: {
        type: Array as () => Expense[],
        required: true,
      },
    },
    setup(props) {
      const total = computed(() => {
        return props.expenses.reduce((sum, expense) => sum + expense.amount, 0).toFixed(2);
      });
  
      return { total };
    },
  });
  </script>
