// src/Elsa.Dashboard/src/nested-drivers/he-radio-options-driver.tsx
import { ActivityModel, ActivityPropertyDescriptor } from "../models/elsa-interfaces";
import { h } from "@stencil/core";
import { getOrCreateProperty } from "../utils/utils";
import { HePropertyDisplayDriver } from "./display-managers/display-manager";
import { HeActivityPropertyDescriptor, NestedActivityDefinitionProperty, NestedProperty } from "../models/custom-component-models";

export class HeRadioOptionsDriver implements HePropertyDisplayDriver {

  display(activity: ActivityModel, property: ActivityPropertyDescriptor) {
    console.log('display() function called from he-radio-options-driver.tsx; data in TYPE ActivityModel:', activity);
    console.log('display() function called from file he-radio-options-driver.tsx; data in TYPE ActivityPropertyDescriptor:', property);
    const prop = getOrCreateProperty(activity, property.name);
    return <he-radio-options-property activityModel={activity} propertyDescriptor={property as HeActivityPropertyDescriptor} propertyModel={prop as NestedActivityDefinitionProperty} />;
  }

  displayNested(activity: ActivityModel, property: NestedProperty, onExpressionChanged: Function) {
    console.log('displayNested() function called from he-radio-options-driver.tsx file; data in TYPE ActivityModel:', activity);
    console.log('displayNested() function called from he-radio-options-driver.tsx file; data in TYPE NestedProperty:', property);
    return <he-radio-options-property activityModel={activity} propertyDescriptor={property.descriptor} propertyModel={property.value} onExpressionChanged={e => onExpressionChanged(e, property)} />;
  }
}

// src/Elsa.Dashboard.Angular/src/drivers/he-radio-options-driver.ts
import { PropertyDisplayDriver } from '../services/property-display-driver';
import { ActivityDefinitionProperty, ActivityModel, ActivityPropertyDescriptor, IntellisenseContext } from '../models';
import { getOrCreateProperty, setActivityModelProperty } from '../utils/utils';
import { Injectable, signal, Signal, Type } from '@angular/core';
import { HeRadioOptionProperty } from 'src/components/common-properties/he-radio-option-property/he-radio-option-property';

@Injectable({
  providedIn: 'root',
})
export class HeRadioOptionsDriver implements PropertyDisplayDriver {
  constructor() {
    console.log('HeRadioOptionsDriver initialized');
  }

  display(model: Signal<ActivityModel>, property: Signal<ActivityPropertyDescriptor>, onUpdated?: () => void, isEncrypted?: boolean) {
    console.log('HeRadioOptions Driver Setup');
    console.log('Activity Model', model());
    console.log('Property Model', property());
    const propertyModel = getOrCreateProperty(model(), property().name);
    const propertyModelSignal = signal<ActivityDefinitionProperty>(propertyModel);

    console.log('property model for HeRadioOptions Driver', propertyModel);
    return {
      componentType: HeRadioOptionProperty,
      inputs: {
        activityModel: model,
        propertyDescriptor: property,
        propertyModel: propertyModelSignal
      },
    };
  }
}
